spring:
  application:
    name: carreraDePods
  datasource:
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
    url: "jdbc:h2:mem:carreras;DB_CLOSE_ON_EXIT=FALSE"
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc.html